# This file is part of eremote-mini-sample.
# https://github.com/garaemon/eremote-mini-sample

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2017, Ryohei Ueda <garaemon@gmail.com>

language: python

python:
    - "3.2"
    - "3.3"
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
